### ISSUE TITLE
No transparency with picom-git

### ISSUE THREAD

**Issue by endorphinsu** [criticalsoft/Theme_GTK#1]
I see from the install script that this is meant for debian-based distros. I use arch and picom-git, instead of compton, because it is unmaintained and not in official repos. What would i need to do to make it work with picom-git or am i forced to use compton?

**Comment by criticalsoft** [comment]
Sorry for late reply i didn't noticed there had an issue.
It Seems picom Based On Compton, So Download Compton Config From:
#XFCE + Compton
#xdg-open "https://www.youtube.com/watch?v=LJVgE7yn7Cs&list=PLUM-aSm--rfkSpViz1cHZ6GI5CS-2JPuH"
And Compare To Your picom Config.
